name: CI

on:
  workflow_dispatch: 
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Typecheck
        run: bun run typecheck

      - name: Lint
        run: bun run lint
