name: Update GitHub GraphQL Schema

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Download GitHub GraphQL Schema
        run: bun run schema:download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Types
        run: bun run schema:codegen

      - name: Update Package Version
        id: bump
        run: |
          NEW_VERSION=$(bun run --silent pkg:bump)
          echo "NEXT_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit-message: "feat: updated github graphql schema"
          title: "feat: updated github graphql schema"
          body: |
            This is an automated PR to update the GitHub GraphQL Schema.

            The new version is ${{ steps.bump.outputs.NEXT_VERSION }}.

            If you have any questions or suggestions, please open an issue.
          branch: update-github-graphql-schema
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass

